### ISSUE TITLE
Teensy 3.2 - reverse echo example not echoing

### ISSUE THREAD

**Issue by dimitre** [bakercp/PacketSerial#8] opened 2016-10-18 12:59 UTC
Hello @bakercp thanks for this library and ofxSerial too. 
I'm trying to run the examples in a Teensy 3.2 and answer is not coming back.
I've tried different baud rates and I suppose onPacket is not firing. I've tried to check turning on the built in LED inside the onPacket function.
Thanks

**Comment by toyfoo** [comment] 2017-02-06 09:06
I have a similar issue with an Arduino ADK and OF 0.9.8. All compiles well, but no communication is happening.

**Comment by ohhorob** [comment] 2017-11-05 14:51
@dimitre can you provide complete sample code?

**Comment by bakercp** [comment] 2017-11-10 05:41
I am not able to reproduce this with the master branch of oF / ofxSerial / ofxIO, etc.

**Comment by bakercp** [comment] 2017-11-10 21:45
I just double checked this with the latest versions of the addons and examples and the master branch of openFrameworks with a Teensy 3.2 and everything is working.  Closing thsi for now.

**Closed by bakercp** 2017-11-10 21:45 UTC

**Comment by randaz81** [comment] 2019-08-20 15:58
@bakercp  I have the same issue with an **Elegoo Mega 2560 R3**.
I uploaded the reverse echo example and I used the serial monitor to test it, but I get no answer. The problem seems to be in the callback because if I just put a myPacketSerial.send() in the main loop, than I'm able to see the message....
